### PR TITLE
feat: Add current folder context for file list actions

### PR DESCRIPTION
**Pull request by Pytal**
Part of https://github.com/nextcloud/server/issues/5534

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
While I do get the point of object parameters, mixing both seems weird. I would pass the directory directly, not within an object.

**Comment by skjnldsv** [comment]
Next release is a minor, let's wait for this PR to be in before releasing the next minor?

**Comment by susnux** [comment]
> Next release is a minor, let's wait for this PR to be in before releasing the next minor?

No 3.10.0 was never released so we can put it into 3.10.0

**Review by susnux — APPROVED** [review]

**Comment by susnux** [comment]
Damn did not saw the auto merge

**Comment by susnux** [comment]
> While I do get the point of object parameters, mixing both seems weird. I would pass the directory directly, not within an object.

Having more than (I think 2, others say 3) parameters is often a mess, especially when this is only passing options.
So in most cases it makes sense to have:

```js
function doSomething(value, options)
```

so you do not end up with a lot of parameters.

But on the other hand having many parameters / options means that your function should be refactored as it is doing to many things and probably can be split...

**Comment by skjnldsv** [comment]
Aaaand now it's released... Was a bit fast and ignoring my comment @susnux

**Pull request merged**
