### PR TITLE
enh(dav): Add support for public `webdav` endpoint

### PR DESCRIPTION
**Pull request by susnux**
We need a different remote address and root path.
Also we can not use `getCurrentUser` for setting the owner.

But more important we need to set additional authentication.

### CODE REVIEW

**Review by skjnldsv — COMMENTED** [review]
Goal was for me to have https://github.com/nextcloud/server/pull/32400 in, but lacked time

**Comment by susnux** [comment]
> Goal was for me to have https://github.com/nextcloud/server/pull/32400 in, but lacked time

Looks good (no idea about the GET part, seems to be off standard?) but the one time authentication looks good.
But we would have to backport that to 27.1, so I think a fix on this library would be easier?

**Comment by skjnldsv** [comment]
> idea about the GET part, seems to be off standard?)

Default behaviour of our dav server, you can also download files from dav with https on our current system :)

**Comment by skjnldsv** [comment]
> Goal was for me to have [nextcloud/server#32400](https://github.com/nextcloud/server/pull/32400) in, but lacked time

is now merged

**Comment by susnux** [comment]
> is now merged

29 feature only? Then I will have a look how to fix it for 27 and 28.

**Comment by susnux** [comment]
Fixed for the filepicker, for this library we should probably go with the new 29 endpoint

**Pull request closed without merging**
