### PR TITLE
formatFileSize() must use only the language, not the locale.

### PR DESCRIPTION
**Pull request by rotdrop**
formatFileSize() use Number.toLocaleString(LOCALE) and passes
getCanonicalLocale() to it. This is wrong, as at least for recent FF
and Chromium browsers toLocaleString() only accepts the language tag,
see for example

https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString

and the demo on that site.

However, getCanonicalLocale() finally return $('html').data('locale'),
replacing _ by _. This results for example in LOCALE=de-DE.UTF-8 and
leads to a

Error: invalid language tag: "de-DE.UTF-8"

The bug is only triggered when the first digit of the fractional part
of the size is != 0, which probably is the reason why the bug is not
triggered so often.

Signed-off-by: Claus-Justus Heine <himself@claus-justus-heine.de>

### CODE REVIEW

**Comment by ChristophWurst** [comment]
The code here was originally at https://github.com/nextcloud/server/blob/9727c020cae7334bd8975f5368c84a8b82ac7d28/core/js/js.js#L1850-L1875. IIRC I coped the logic over without giving it too much thought.

Could we have a test for this in https://github.com/nextcloud/nextcloud-files/blob/master/test/humanFileSize.test.js?

**Comment by skjnldsv** [comment]
@rotdrop any news? :)

**Comment by susnux** [comment]
Using the language is not correct. Language defines the language and not the locale, meaning I can configure Nextcloud to use the US-English language but still use German locale to keep `,` as decimal separator or to keep *Monday* as the start of the week instead of Sunday or to keep the date format.

**Comment by susnux** [comment]
> Error: invalid language tag: "de-DE.UTF-8"

I would say this is a invalid locale string as it contains the encoding, it should only contain BCP 47 compatible strings. Meaning we should fix this on l10n library (while I could not reproduce that issue when setting different locales on the Nextcloud settings).

**Pull request closed without merging**
